fork = false
frame = "full"
idle = true
maximized = true
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = false
wsl = false

[font]
normal = ['Iosevka Nerd Font'] # Will use the bundled Fira Code Nerd Font by default
size = 10.0
